# Generated by Django 5.1 on 2025-04-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posterName', models.CharField(max_length=100)),
                ('original', models.IntegerField()),
                ('wish', models.IntegerField()),
                ('subjects', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('acceptorName', models.CharField(max_length=100)),
            ],
        ),
    ]
