# Generated by Django 5.1 on 2025-04-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0003_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subjects',
        ),
        migrations.AddField(
            model_name='post',
            name='subjects',
            field=models.ManyToManyField(to='college_app.subject'),
        ),
    ]
