# Generated by Django 5.1 on 2025-04-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0004_remove_post_subjects_post_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='acceptorTelegram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='posterTelegram',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
