# Generated by Django 5.1 on 2025-04-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0005_post_acceptortelegram_post_postertelegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='acceptorTelegram',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
